### ISSUE TITLE
Error on saving sign to gallery

### ISSUE THREAD

**Issue by YornSokha** [4Q-s-r-o/signature#51]
I faced this error when I tried to save the image after generated :
E/flutter ( 3742): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method saveImageToGallery on channel image_gallery_saver)
E/flutter ( 3742): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 3742): <asynchronous suspension>
E/flutter ( 3742): #1      ImageGallerySaver.saveImage (package:image_gallery_saver/image_gallery_saver.dart:20:9)
E/flutter ( 3742): <asynchronous suspension>
E/flutter ( 3742): #2      _GetdocsignState.build.<anonymous closure> (package:gsdoc_mobile_v2/getdoc/getdocsign.dart:207:60)
E/flutter ( 3742): <asynchronous suspension>
E/flutter ( 3742):

**Comment by MartinHlavna** [comment]
Hi, 
this looks like problem in ```image_gallery_saver``` library.

**Comment by MartinHlavna** [comment]
Closing as this is not related to this plugin. If you are sure this is problem in Signature feel free to reopen and share your implementation so we can see where is problem between cooperation of two plugins. 

Since exported data from Signature are PNG bytes, you should be free to do anything you like with it.
