### ISSUE TITLE
Multi Features

### ISSUE THREAD

**Issue by mstfkhazaal** [4Q-s-r-o/signature#63]
1- Please add Placeholder when user not drawing yet
![placholder](https://user-images.githubusercontent.com/47450090/178909175-a33c2398-f6a9-4797-93cf-3aaf8e98fa80.png)
2- Add ToSVG & To PDF

**Comment by MartinHlavna** [comment]
Hi,
thanks for the ideas.

1) Since this is design requirement I would suggest implementing this outside of the the plugin. You can position your placeholder on top of the Signature pad and hide on the first tap. You will probably loose first point, but that should be irrelevant as next one would be probably on the same position. 

2) As for toSVG see #9. I would say conversion toPDF is also a bit out of the scope of this package, bacause there are many variables and most users probably wants to include singature in PDF along with some other data, not just signature alone. What is your use case for this?
