### ISSUE TITLE
Impella ready?

### ISSUE THREAD

**Issue by llorenzo** [4Q-s-r-o/signature#77]
[VERBOSE-2:validation.cc(27)] Cannot bind vertex buffer with an unknown index type.
[VERBOSE-2:validation.cc(38)] Break on ImpellerValidationBreak to inspect point of failure.

**Comment by MartinHlavna** [comment]
Hello,

can you be more elaborate on this? How does application behave and what is not working? I am not sure about what impella is. My first thought was it was name for certain iOS or macOS version but I was unable to google anything sensible. 

Even then, since this is 100% dart package with no native code it should work just fine. Only the web version required to code different export method.
