### ISSUE TITLE
Save a Signature in Memory or local for ftp Upload ?

### ISSUE THREAD

**Issue by berkayhh** [4Q-s-r-o/signature#80]
Hey ,
I wanna export a Signature for Ftp upload , I tried maybe 1000 different ways but im getting the Problem Future Uint64 ist not string type , If I click on save button , function will get this signature and covert to png and upload to my Hosting with pub FtpConnect , must I first save it on local Storage or can i upload direct to hosting with ftp ? 
Thanks for u Help.

**Comment by MartinHlavna** [comment]
Hello,

as far as i know, there should be any requirements for local storage saving. However it may vary depending on how you upload your data.  If for example package for FTP requires you to have local file, then there is nothing signature can do about it. 

In our project we save locally because we want to upload later (when device has network connectivity) via HTTP.
If the problem is "Uint64 is not string type" I would look at why you need to use string when working with binary data. 

If you really need to send binary data as string I would suggest base64 and maybe also utf8 encodings.
